# permissions for end users to view services.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-viewer-role
rules:
- apiGroups:
  - frp.1eb100.net
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - frp.1eb100.net
  resources:
  - services/status
  verbs:
  - get
